version: "1.0"
services:
  web:
    build: pool-temp-web
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - backend

  backend:
    build: pool-temp-backend
    ports:
      - "3001:3000"
    networks:
      - postgres
      - web
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  web:
    driver: bridge