version: "1.0"
services:
  backend:
    build: pool-temp-backend
    ports:
      - "3001:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data