version: "3.9"
services:
  web:
    build: pool-temp-web
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - backend

  backend:
    build: pool-temp-backend

    ports:
      - "3001:3000"
    networks:
      - postgres
      - web
    depends_on:
      - db
    environment:
      - DB_NAME=mydb
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge
  web:
    driver: bridge