import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {
  const res = await fetch("http://localhost:3001/api/v1/measurements/current");
  const measurement = await res.json();

  return {
    props: {
      temperature: measurement.value,
      timestamp: measurement.timestamp,
    },
    revalidate: 60,
  };
}

function calculateMinutesAgo(otherDate: Date): number {
  const currentDate: Date = new Date();
  const difference = currentDate.getTime() - otherDate.getTime();
  return Math.floor(difference / 1000 / 60);
}
export default function Home({
  temperature,
  timestamp,
}: {
  temperature: number;
  timestamp: string;
}) {
  const parsedTimestamp: Date = new Date(Date.parse(timestamp));
  const minutesDifference = calculateMinutesAgo(parsedTimestamp);
  return (
    <>
      <Head>
        <title>PoolTemp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container m-8">
        <p className="text-2xl">Current temperature: {temperature}°C</p>
        <p>Measurement taken: {parsedTimestamp.toLocaleString()}</p>
        {minutesDifference < 60 && minutesDifference > 0 && (
          <p>{minutesDifference} Minutes ago</p>
        )}
        {minutesDifference === 0 && <p>Just now</p>}
      </div>
    </>
  );
}
