import Head from "next/head";
import {Inter} from "next/font/google";
import React from "react";
import SensorCard from "@/components/sensor-card";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
    // <Line data={data}></Line>
    // SensorCard -> Displays the current temperature of a sensor + chart of the last 24h // use getStaticProps to load list of sensors, revalidate every 15s
    return (
        <>
            <Head>
                <title>PoolTemp</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="pt-12 text-white">
                <div className="flex flex-wrap">
                    <SensorCard></SensorCard>
                    <SensorCard></SensorCard>
                    <SensorCard></SensorCard>
                    <SensorCard></SensorCard>
                    <SensorCard></SensorCard>
                </div>
            </div>
        </>
    );
}
